root = "/app"
testdata_dir = "testdata"
tmp_dir = "/tmp/air-auth"

[build]
  args_bin = []
  bin = "/tmp/air-auth/auth-main"
  cmd = "go build -o /tmp/air-auth/auth-main status-page/packages/auth/cmd/auth-server"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "dist", "node_modules", "data", "packages/web", "packages/api", "packages/status-probe-worker"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["packages/auth", "packages/core"]
  include_ext = ["go", "proto"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 500
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
